// StanceLoop Calisthenics Curriculum — Comprehensive Progressive Roadmaps
// Pure TypeScript: zero React/DOM imports. Portable core for web/native.
// Contains 7 difficulty levels, 75 calisthenics skills + progressions

import type { DrillId } from "../types";

export type CalisthenicsLevel = 0 | 1 | 2 | 3 | 4 | 5 | 6;
export type CalisthenicsCategory = "push" | "pull" | "core" | "legs" | "skill";

export interface CalisthenicsExercise {
  id: string;
  name: string;
  category: CalisthenicsCategory;
  level: CalisthenicsLevel;
  description: string;
  prerequisites: string[]; // Exercise IDs that must be mastered first
  progressions: string[]; // Next exercise IDs in the chain
  targetReps?: number;
  targetHoldSeconds?: number;
  targetSets?: number;
  restSeconds?: number;
  coachingCues: string[];
  commonFaults: string[];
}

export interface CalisthenicsLevelData {
  level: CalisthenicsLevel;
  name: string;
  description: string;
  exercises: CalisthenicsExercise[];
}

// ============================================================================
// LEVEL 0: NONE (Absolute Baseline)
// ============================================================================
export const LEVEL_0_EXERCISES: CalisthenicsExercise[] = [
  {
    id: "wall_pushup",
    name: "Wall Push-up",
    category: "push",
    level: 0,
    description: "Pushing against a wall to reduce bodyweight resistance and build initial pressing mechanics.",
    prerequisites: [],
    progressions: ["incline_pushup"],
    targetReps: 20,
    targetSets: 3,
    restSeconds: 60,
    coachingCues: ["Hands shoulder-width at chest height", "Body straight line", "Elbows 45° from torso", "Control the descent"],
    commonFaults: ["Sagging hips", "Elbows flared", "Not full range", "Rushing reps"],
  },
  {
    id: "dead_hang",
    name: "Dead Hang",
    category: "pull",
    level: 0,
    description: "Hanging from a bar to build grip strength and shoulder blade control.",
    prerequisites: [],
    progressions: ["scapular_pullup"],
    targetHoldSeconds: 30,
    targetSets: 3,
    restSeconds: 90,
    coachingCues: ["Shoulder-width grip", "Active shoulders (depress scapulae)", "Hollow body position", "Breathe calmly"],
    commonFaults: ["Passive shoulders", "Kipping/swinging", "Grip failure", "Holding breath"],
  },
  {
    id: "knee_plank",
    name: "Knee Plank",
    category: "core",
    level: 0,
    description: "Core stability built on forearms and knees — reduced lever arm for beginners.",
    prerequisites: [],
    progressions: ["standard_plank"],
    targetHoldSeconds: 30,
    targetSets: 3,
    restSeconds: 60,
    coachingCues: ["Elbows under shoulders", "Posterior pelvic tilt", "Squeeze glutes", "Head neutral"],
    commonFaults: ["Sagging hips", "Piked hips", "Shrugged shoulders", "Holding breath"],
  },
  {
    id: "assisted_squat",
    name: "Assisted Squat",
    category: "legs",
    level: 0,
    description: "Holding onto a pole/door frame for balance while learning squat mechanics.",
    prerequisites: [],
    progressions: ["air_squat"],
    targetReps: 15,
    targetSets: 3,
    restSeconds: 60,
    coachingCues: ["Feet shoulder-width", "Sit back and down", "Knees track toes", "Chest up"],
    commonFaults: ["Heels lifting", "Knees caving", "Forward lean", "Shallow depth"],
  },
];

// ============================================================================
// LEVEL 1: BEGINNER (Foundational Strength)
// ============================================================================
export const LEVEL_1_EXERCISES: CalisthenicsExercise[] = [
  {
    id: "incline_pushup",
    name: "Incline Push-up",
    category: "push",
    level: 1,
    description: "Hands elevated on a bench/box to reduce bodyweight while maintaining horizontal pressing pattern.",
    prerequisites: ["wall_pushup"],
    progressions: ["standard_pushup"],
    targetReps: 12,
    targetSets: 3,
    restSeconds: 90,
    coachingCues: ["Hands on bench/box", "Body straight line", "Chest to bench", "Elbows 45°"],
    commonFaults: ["Sagging hips", "Elbows flared", "Not touching chest", "Piked hips"],
  },
  {
    id: "scapular_pullup",
    name: "Scapular Pull-up",
    category: "pull",
    level: 1,
    description: "Activating the shoulders from a dead hang without bending the elbows — teaches scapular depression.",
    prerequisites: ["dead_hang"],
    progressions: ["australian_pullup"],
    targetReps: 10,
    targetSets: 3,
    restSeconds: 90,
    coachingCues: ["From dead hang", "Depress scapulae only", "Arms stay straight", "Pause at top"],
    commonFaults: ["Bending elbows", "Shrugging shoulders", "Using momentum", "Partial range"],
  },
  {
    id: "australian_pullup",
    name: "Australian Pull-up (Bodyweight Row)",
    category: "pull",
    level: 1,
    description: "Pulling chest to a low bar with feet on the ground — horizontal pulling foundation.",
    prerequisites: ["scapular_pullup"],
    progressions: ["negative_pullup"],
    targetReps: 10,
    targetSets: 3,
    restSeconds: 90,
    coachingCues: ["Body straight", "Pull chest to bar", "Squeeze shoulder blades", "Control descent"],
    commonFaults: ["Sagging hips", "Incomplete pull", "Flaring elbows", "Kipping"],
  },
  {
    id: "air_squat",
    name: "Full Bodyweight Squat",
    category: "legs",
    level: 1,
    description: "Dropping hips below parallel with heels flat — fundamental lower body movement.",
    prerequisites: ["assisted_squat"],
    progressions: ["jump_squat"],
    targetReps: 20,
    targetSets: 3,
    restSeconds: 90,
    coachingCues: ["Feet shoulder-width", "Hip crease below knee", "Heels glued", "Chest proud"],
    commonFaults: ["Heels lift", "Knees cave", "Forward lean", "Shallow depth"],
  },
  {
    id: "lying_leg_raise",
    name: "Lying Leg Raise",
    category: "core",
    level: 1,
    description: "Building lower abdominal strength on the floor with straight legs.",
    prerequisites: ["knee_plank"],
    progressions: ["hanging_knee_raise"],
    targetReps: 12,
    targetSets: 3,
    restSeconds: 60,
    coachingCues: ["Lower back pressed flat", "Legs straight", "Controlled lowering", "Don't touch floor"],
    commonFaults: ["Arching back", "Bending knees", "Dropping legs fast", "Using momentum"],
  },
  {
    id: "negative_pullup",
    name: "Negative Pull-up",
    category: "pull",
    level: 1,
    description: "Lowering from chin-over-bar as slowly as possible — builds the pulling strength path for full pull-ups.",
    prerequisites: ["australian_pullup"],
    progressions: ["standard_pullup"],
    targetReps: 5,
    targetSets: 3,
    restSeconds: 120,
    coachingCues: ["Jump or step to top", "Lower 3-5 seconds", "Keep shoulders active", "Control to dead hang"],
    commonFaults: ["Dropping fast", "Passive shoulders", "Bending elbows early", "Kicking legs"],
  },
  {
    id: "bench_dip",
    name: "Bench Dip",
    category: "push",
    level: 1,
    description: "Triceps dip with hands on a bench and feet on the floor — prepares the dip pressing pattern.",
    prerequisites: ["incline_pushup"],
    progressions: ["parallel_dip"],
    targetReps: 12,
    targetSets: 3,
    restSeconds: 90,
    coachingCues: ["Hands shoulder-width behind", "Elbows point back", "Lower until arms parallel", "Keep hips close"],
    commonFaults: ["Elbows flared", "Dropping too deep", "Shrugging shoulders", "Legs doing the work"],
  },
  {
    id: "standard_plank",
    name: "Standard Plank",
    category: "core",
    level: 1,
    description: "Full forearm plank with stacked body position — the core stability baseline.",
    prerequisites: ["knee_plank"],
    progressions: ["hanging_knee_raise", "side_plank"],
    targetHoldSeconds: 60,
    targetSets: 3,
    restSeconds: 60,
    coachingCues: ["Elbows under shoulders", "Glutes squeezed", "Ribs down", "Breathe steadily"],
    commonFaults: ["Sagging hips", "Piked hips", "Holding breath", "Shrugged shoulders"],
  },
];

// ============================================================================
// LEVEL 2: INTERMEDIATE (The Golden Standard)
// ============================================================================
export const LEVEL_2_EXERCISES: CalisthenicsExercise[] = [
  {
    id: "standard_pushup",
    name: "Standard Push-up",
    category: "push",
    level: 2,
    description: "Strict form with rigid spine and chest touching the floor — the gold standard.",
    prerequisites: ["incline_pushup"],
    progressions: ["decline_pushup", "diamond_pushup", "archer_pushup"],
    targetReps: 20,
    targetSets: 3,
    restSeconds: 120,
    coachingCues: ["Chest to floor", "Body rigid", "Elbows 45°", "Full lockout"],
    commonFaults: ["Sagging hips", "Half reps", "Flared elbows", "Piked hips"],
  },
  {
    id: "standard_pullup",
    name: "Standard Pull-up / Chin-up",
    category: "pull",
    level: 2,
    description: "Full range of motion from dead hang to chin over bar.",
    prerequisites: ["australian_pullup", "negative_pullup"],
    progressions: ["l_sit_pullup", "chest_to_bar_pullup", "weighted_pullup"],
    targetReps: 10,
    targetSets: 3,
    restSeconds: 120,
    coachingCues: ["Dead hang start", "Chin over bar", "Control descent", "Full extension"],
    commonFaults: ["Kipping", "Chin not over", "Partial range", "Chicken wing"],
  },
  {
    id: "parallel_dip",
    name: "Parallel Bar Dip",
    category: "push",
    level: 2,
    description: "Lowering body until shoulders pass below elbows on free bars.",
    prerequisites: ["standard_pushup", "bench_dip"],
    progressions: ["straight_bar_dip", "weighted_dip", "korean_dip"],
    targetReps: 10,
    targetSets: 3,
    restSeconds: 120,
    coachingCues: ["Shoulders below elbows", "Lean forward slightly", "Elbows back", "Full lockout"],
    commonFaults: ["Not low enough", "Flared elbows", "Shrugging", "Incomplete lockout"],
  },
  {
    id: "decline_pushup",
    name: "Decline Push-up",
    category: "push",
    level: 2,
    description: "Feet elevated on a bench to target upper chest and shoulders.",
    prerequisites: ["standard_pushup"],
    progressions: ["pike_pushup", "pseudo_planche_pushup"],
    targetReps: 12,
    targetSets: 3,
    restSeconds: 120,
    coachingCues: ["Feet elevated", "Shoulders over hands", "Head to floor", "Push tall"],
    commonFaults: ["Arching back", "Piked hips", "Head not to floor", "Rushing"],
  },
  {
    id: "hanging_knee_raise",
    name: "Hanging Knee Raise",
    category: "core",
    level: 2,
    description: "Lifting knees to chest while hanging — dynamic core strength.",
    prerequisites: ["lying_leg_raise", "dead_hang"],
    progressions: ["hanging_leg_raise", "l_sit", "toes_to_bar"],
    targetReps: 12,
    targetSets: 3,
    restSeconds: 90,
    coachingCues: ["Active hang", "Knees to chest", "Control descent", "No swinging"],
    commonFaults: ["Swinging", "Partial raise", "Grip failure", "Rushing"],
  },
  {
    id: "wide_pushup",
    name: "Wide Push-up",
    category: "push",
    level: 2,
    description: "Hands placed wider than shoulders to shift load onto the chest — a prerequisite for the archer push-up.",
    prerequisites: ["standard_pushup"],
    progressions: ["archer_pushup"],
    targetReps: 12,
    targetSets: 3,
    restSeconds: 120,
    coachingCues: ["Hands 1.5x shoulder width", "Chest to floor", "Elbows track hands", "Full lockout"],
    commonFaults: ["Too narrow", "Sagging hips", "Half reps", "Flared elbows"],
  },
  {
    id: "parallel_support_hold",
    name: "Parallel Bar Support Hold",
    category: "skill",
    level: 2,
    description: "Holding body weight locked out on parallel bars — the foundation for dips and the L-sit.",
    prerequisites: ["bench_dip"],
    progressions: ["l_sit"],
    targetHoldSeconds: 30,
    targetSets: 3,
    restSeconds: 90,
    coachingCues: ["Lock arms fully", "Depress shoulders", "Legs straight", "Tense everything"],
    commonFaults: ["Bent arms", "Shrugging", "Swinging legs", "Short holds"],
  },
  {
    id: "pike_pushup",
    name: "Pike Push-up",
    category: "push",
    level: 2,
    description: "Hips high in a pike position, pressing the head toward the floor — a scaled handstand push-up.",
    prerequisites: ["decline_pushup"],
    progressions: ["wall_handstand", "90_degree_pushup"],
    targetReps: 8,
    targetSets: 3,
    restSeconds: 120,
    coachingCues: ["Hips over shoulders", "Head to floor", "Elbows 45°", "Push tall"],
    commonFaults: ["Arching back", "Bent knees", "Head not to floor", "Partial range"],
  },
  {
    id: "wall_walk",
    name: "Wall Walk",
    category: "skill",
    level: 2,
    description: "Walking feet up the wall into a handstand position and back down — building confidence upside down.",
    prerequisites: ["pike_pushup"],
    progressions: ["wall_handstand"],
    targetReps: 5,
    targetSets: 3,
    restSeconds: 120,
    coachingCues: ["Step hands back", "Walk feet up", "Push floor away", "Control the way down"],
    commonFaults: ["Arching", "Rushing", "Bent arms", "Kicking off wall"],
  },
  {
    id: "bulgarian_split_squat",
    name: "Bulgarian Split Squat",
    category: "legs",
    level: 2,
    description: "Rear foot elevated split squat — unilateral leg strength on the road to the pistol squat.",
    prerequisites: ["air_squat"],
    progressions: ["pistol_squat", "assisted_pistol"],
    targetReps: 8,
    targetSets: 3,
    restSeconds: 120,
    coachingCues: ["Rear foot elevated", "Front knee tracks toe", "Torso tall", "Full depth"],
    commonFaults: ["Leaning forward", "Knee caves", "Shallow depth", "Heel lifts"],
  },
  {
    id: "assisted_pistol",
    name: "Assisted Pistol Squat",
    category: "legs",
    level: 2,
    description: "Single-leg squat using a counterbalance or support — the final stepping stone to the pistol.",
    prerequisites: ["bulgarian_split_squat"],
    progressions: ["pistol_squat"],
    targetReps: 5,
    targetSets: 3,
    restSeconds: 120,
    coachingCues: ["Sit back", "Non-working leg forward", "Counterbalance arms", "Control the bottom"],
    commonFaults: ["Heel lifts", "Over-relying on support", "Knee caves", "Rushing"],
  },
  {
    id: "side_plank",
    name: "Side Plank",
    category: "core",
    level: 2,
    description: "Holding the body straight on one forearm — oblique strength required for the human flag.",
    prerequisites: ["standard_plank"],
    progressions: ["human_flag"],
    targetHoldSeconds: 30,
    targetSets: 3,
    restSeconds: 90,
    coachingCues: ["Elbow under shoulder", "Body straight", "Stack hips", "Push through forearm"],
    commonFaults: ["Hips sag", "Rolling", "Bent body", "Holding breath"],
  },
  {
    id: "weighted_dip",
    name: "Weighted Dip",
    category: "push",
    level: 2,
    description: "Parallel bar dip with added weight — building the pressing strength behind the impossible dip.",
    prerequisites: ["parallel_dip"],
    progressions: ["impossible_dip"],
    targetReps: 6,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Shoulders below elbows", "Controlled descent", "Full lockout", "Stable weight"],
    commonFaults: ["Too much weight", "Flared elbows", "Shallow depth", "Swinging"],
  },
];

// ============================================================================
// LEVEL 3: ADVANCED (Skill Entry — True Body Manipulation)
// ============================================================================
export const LEVEL_3_EXERCISES: CalisthenicsExercise[] = [
  {
    id: "archer_pushup",
    name: "Archer Push-up",
    category: "push",
    level: 3,
    description: "Sliding side-to-side, forcing one arm to take majority of the weight — unilateral pushing.",
    prerequisites: ["standard_pushup", "wide_pushup"],
    progressions: ["one_arm_pushup", "pseudo_planche_pushup"],
    targetReps: 8,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Wide hand placement", "One arm straight", "Shift weight laterally", "Chest to working hand"],
    commonFaults: ["Bending straight arm", "Not shifting enough", "Rotating torso", "Rushing"],
  },
  {
    id: "l_sit",
    name: "L-Sit",
    category: "skill",
    level: 3,
    description: "Holding legs perfectly straight and parallel to ground while supporting weight on hands.",
    prerequisites: ["hanging_knee_raise", "parallel_support_hold"],
    progressions: ["v_sit", "l_sit_to_handstand"],
    targetHoldSeconds: 15,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Hands shoulder-width", "Depress shoulders", "Legs locked straight", "Toes pointed", "Compress hard"],
    commonFaults: ["Bent knees", "Shoulders shrugged", "Low legs", "Losing compression"],
  },
  {
    id: "wall_handstand",
    name: "Wall-Assisted Handstand",
    category: "skill",
    level: 3,
    description: "Building shoulder strength and balance required to flip upside down safely.",
    prerequisites: ["pike_pushup", "wall_walk"],
    progressions: ["freestanding_handstand", "handstand_pushup"],
    targetHoldSeconds: 30,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Walk up wall", "Stomach to wall", "Push floor away", "Hollow body", "Gaze between hands"],
    commonFaults: ["Arched back", "Shoulders closed", "Banana shape", "Fingers loose"],
  },
  {
    id: "pistol_squat",
    name: "Pistol Squat",
    category: "legs",
    level: 3,
    description: "Full single-leg squat requiring extreme balance, flexibility, and power.",
    prerequisites: ["air_squat", "bulgarian_split_squat", "assisted_pistol"],
    progressions: ["weighted_pistol", "pistol_jump"],
    targetReps: 5,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Non-working leg forward", "Sit back", "Knee tracks toe", "Counterbalance arms"],
    commonFaults: ["Heel lifts", "Knee caves", "Rushing down", "Losing balance"],
  },
  {
    id: "hanging_leg_raise",
    name: "Hanging Straight Leg Raise",
    category: "core",
    level: 3,
    description: "Lifting toes all the way to touch the pull-up bar — full core compression.",
    prerequisites: ["hanging_knee_raise", "l_sit"],
    progressions: ["toes_to_bar", "windshield_wiper", "dragon_flag"],
    targetReps: 8,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Active hang", "Legs straight", "Toes to bar", "Controlled lowering"],
    commonFaults: ["Bent knees", "Swinging", "Partial range", "Grip failure"],
  },
  {
    id: "chest_to_bar_pullup",
    name: "Chest-to-Bar Pull-up",
    category: "pull",
    level: 3,
    description: "Pulling until the chest touches the bar — the power prerequisite for the muscle-up.",
    prerequisites: ["standard_pullup"],
    progressions: ["muscle_up"],
    targetReps: 8,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Pull to chest", "Elbows back", "Retract scapulae", "Explosive pull"],
    commonFaults: ["Chin only", "Kipping", "Shallow pull", "Arching"],
  },
  {
    id: "straight_bar_dip",
    name: "Straight Bar Dip",
    category: "push",
    level: 3,
    description: "Pressing on a straight bar (as in a muscle-up) rather than parallel bars — a stronger grip angle.",
    prerequisites: ["parallel_dip"],
    progressions: ["korean_dip", "impossible_dip"],
    targetReps: 8,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Shoulders below elbows", "Straight bar grip", "Lean slightly", "Full lockout"],
    commonFaults: ["Not deep enough", "Flared elbows", "Wrist strain", "Incomplete lockout"],
  },
  {
    id: "explosive_pullup",
    name: "Explosive Pull-up",
    category: "pull",
    level: 3,
    description: "Pulling with maximum speed to drive the bar toward the chest — the transition power for muscle-ups.",
    prerequisites: ["standard_pullup"],
    progressions: ["muscle_up"],
    targetReps: 6,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Max speed", "Pull to lower chest", "Retract scapulae", "Snap at the top"],
    commonFaults: ["Slow pulls", "Kipping", "Shallow range", "No snap"],
  },
  {
    id: "90_degree_pushup",
    name: "90-Degree Push-up",
    category: "push",
    level: 3,
    description: "Pressing with hips stacked directly over shoulders in a near-vertical line — a brutal pike-push progression.",
    prerequisites: ["pike_pushup", "wall_handstand"],
    progressions: ["freestanding_hspu"],
    targetReps: 5,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Hips over shoulders", "Head to floor", "Elbows tucked", "Body vertical"],
    commonFaults: ["Hips drifting back", "Arched back", "Bent knees", "Shallow range"],
  },
  {
    id: "frog_stand",
    name: "Frog Stand",
    category: "skill",
    level: 3,
    description: "Balancing on hands with knees on triceps — the first tuck planche balance position.",
    prerequisites: ["standard_pushup"],
    progressions: ["tuck_planche"],
    targetHoldSeconds: 20,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Knees on triceps", "Lean forward", "Straight arms", "Find the balance point"],
    commonFaults: ["Bent arms", "Not leaning", "Knees slipping", "Holding breath"],
  },
  {
    id: "pseudo_planche_pushup",
    name: "Pseudo Planche Push-up",
    category: "push",
    level: 3,
    description: "Push-up with hands by the hips and a strong forward lean — building planche-specific pressing strength.",
    prerequisites: ["decline_pushup", "frog_stand"],
    progressions: ["tuck_planche_pushup", "tuck_planche"],
    targetReps: 8,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Hands by hips", "Lean forward hard", "Elbows tucked", "Chest to floor"],
    commonFaults: ["No forward lean", "Hands too far forward", "Elbows flared", "Partial range"],
  },
  {
    id: "tuck_planche_pushup",
    name: "Tuck Planche Push-up",
    category: "push",
    level: 3,
    description: "Pressing up and down while holding a tuck planche — carrying the lean into a full press.",
    prerequisites: ["pseudo_planche_pushup"],
    progressions: ["tuck_planche"],
    targetReps: 5,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Knees tucked", "Straight arms at top", "Lower with control", "Keep the lean"],
    commonFaults: ["Losing the lean", "Bent arms at top", "Knees dropping", "Rushing"],
  },
  {
    id: "dragon_flag_negative",
    name: "Dragon Flag Negative",
    category: "core",
    level: 3,
    description: "Lowering the rigid body from the top position only — the eccentric strength behind the full dragon flag.",
    prerequisites: ["hanging_leg_raise"],
    progressions: ["dragon_flag"],
    targetReps: 5,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Body straight", "Lower slowly", "Hips up first", "No kink"],
    commonFaults: ["Bent hips", "Dropping fast", "Partial descent", "Neck strain"],
  },
  {
    id: "weighted_pullup",
    name: "Weighted Pull-up",
    category: "pull",
    level: 3,
    description: "Pull-up with added weight — the strength base for the one-arm pull-up.",
    prerequisites: ["standard_pullup"],
    progressions: ["one_arm_pullup", "archer_pullup"],
    targetReps: 6,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Dead hang start", "Chin over bar", "Controlled descent", "Stable weight"],
    commonFaults: ["Too much weight", "Kipping", "Partial range", "Swinging"],
  },
  {
    id: "archer_pullup",
    name: "Archer Pull-up",
    category: "pull",
    level: 3,
    description: "Pulling toward one hand while the other arm stays extended — shifting load toward a single arm.",
    prerequisites: ["standard_pullup", "weighted_pullup"],
    progressions: ["one_arm_pullup", "typewriter_pullup"],
    targetReps: 6,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Pull to one hand", "Straight assist arm", "Shift weight", "Chin to working hand"],
    commonFaults: ["Bending assist arm", "Not shifting", "Twisting", "Partial range"],
  },
  {
    id: "typewriter_pullup",
    name: "Typewriter Pull-up",
    category: "pull",
    level: 3,
    description: "Holding the top position and sliding side to side — unilateral lockout strength for the one-arm pull-up.",
    prerequisites: ["archer_pullup"],
    progressions: ["one_arm_pullup"],
    targetReps: 6,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Chin over bar", "Slide shoulder to shoulder", "Stay tall", "Control the slide"],
    commonFaults: ["Dropping down", "Kipping", "Rushing the slide", "Uneven arms"],
  },
  {
    id: "one_arm_hang",
    name: "One-Arm Dead Hang",
    category: "skill",
    level: 3,
    description: "Hanging from a single arm with an active shoulder — grip and shoulder integrity for flags and levers.",
    prerequisites: ["standard_pullup"],
    progressions: ["human_flag"],
    targetHoldSeconds: 30,
    targetSets: 3,
    restSeconds: 120,
    coachingCues: ["Active shoulder", "Neutral grip", "Relaxed body", "Breath steady"],
    commonFaults: ["Dead shoulder", "Swinging", "Grip failure", "Holding breath"],
  },
  {
    id: "korean_dip",
    name: "Korean Dip",
    category: "push",
    level: 3,
    description: "Straight bar dip with the body dipping behind the bar — the extreme range prelude to the impossible dip.",
    prerequisites: ["straight_bar_dip"],
    progressions: ["impossible_dip"],
    targetReps: 5,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Body behind bar", "Shoulders past hands", "Control the dip", "Full press"],
    commonFaults: ["Not behind bar", "Flared elbows", "Too shallow", "Shoulder strain"],
  },
];

// ============================================================================
// LEVEL 4: MASTER (Elite Strength & Leverage)
// ============================================================================
export const LEVEL_4_EXERCISES: CalisthenicsExercise[] = [
  {
    id: "muscle_up",
    name: "Strict Muscle-up",
    category: "skill",
    level: 4,
    description: "Explosive power transition from pull-up into dip above the bar — fluid and controlled.",
    prerequisites: ["chest_to_bar_pullup", "straight_bar_dip", "explosive_pullup"],
    progressions: ["slow_muscle_up", "l_sit_muscle_up", "one_arm_muscle_up"],
    targetReps: 5,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["False grip", "Explosive pull", "Fast transition", "Straight bar dip"],
    commonFaults: ["Kipping", "Chicken wing", "False grip loss", "Chicken wing dip"],
  },
  {
    id: "freestanding_hspu",
    name: "Freestanding Handstand Push-up",
    category: "skill",
    level: 4,
    description: "Lowering head to floor and pushing back up without wall support — balance + strength.",
    prerequisites: ["freestanding_handstand", "wall_hspu", "90_degree_pushup"],
    progressions: ["one_arm_hspu"],
    targetReps: 3,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Balance first", "Head to floor", "Push tall", "Elbows 45°", "Hollow body"],
    commonFaults: ["Falling", "Arching", "Head not to floor", "Banana shape"],
  },
  {
    id: "tuck_planche",
    name: "Tuck Planche",
    category: "skill",
    level: 4,
    description: "Holding entire body off ground balanced only on hands, knees tucked to chest.",
    prerequisites: ["frog_stand", "pseudo_planche_pushup", "tuck_planche_pushup"],
    progressions: ["advanced_tuck_planche", "straddle_planche", "full_planche"],
    targetHoldSeconds: 10,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Lean forward", "Straight arms", "Knees tucked tight", "Round upper back", "Lean more"],
    commonFaults: ["Bent arms", "Straight legs", "Not leaning enough", "Piked hips"],
  },
  {
    id: "dragon_flag",
    name: "Dragon Flag",
    category: "core",
    level: 4,
    description: "Keeping entire body rigid as a plank and pivoting only from shoulders (Bruce Lee style).",
    prerequisites: ["hanging_leg_raise", "dragon_flag_negative"],
    progressions: ["dragon_flag_flutter", "one_arm_dragon_flag"],
    targetReps: 5,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Anchor hands", "Body straight", "Hips up first", "Control down", "No kink"],
    commonFaults: ["Bent hips", "Using momentum", "Partial range", "Neck strain"],
  },
  {
    id: "one_arm_pullup",
    name: "One-Arm Pull-up",
    category: "pull",
    level: 4,
    description: "Pulling entire body weight up using a single arm — ultimate relative strength.",
    prerequisites: ["weighted_pullup", "archer_pullup", "typewriter_pullup"],
    progressions: ["one_arm_chinup", "one_arm_muscle_up"],
    targetReps: 3,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Rotate toward bar", "Pull elbow down", "No rotation", "Control down"],
    commonFaults: ["Twisting", "Kipping", "Not full ROM", "Grip failure"],
  },
  {
    id: "freestanding_handstand",
    name: "Freestanding Handstand",
    category: "skill",
    level: 4,
    description: "Balancing upside down with no wall support — the balance base for handstand push-ups and presses.",
    prerequisites: ["wall_handstand"],
    progressions: ["freestanding_hspu", "one_arm_handstand"],
    targetHoldSeconds: 30,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Stack wrists over shoulders", "Fingers spread", "Tight core", "Look at hands"],
    commonFaults: ["Arching", "Overbalancing", "Bent arms", "Fear of falling"],
  },
  {
    id: "wall_hspu",
    name: "Wall Handstand Push-up",
    category: "push",
    level: 4,
    description: "Handstand push-up with heels resting on the wall — building shoulder pressing strength in the handstand.",
    prerequisites: ["wall_handstand", "90_degree_pushup"],
    progressions: ["freestanding_hspu"],
    targetReps: 5,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Heels light on wall", "Head to floor", "Elbows tucked", "Push to full lockout"],
    commonFaults: ["Banana shape", "Kicking off wall", "Half reps", "Elbows flared"],
  },
  {
    id: "advanced_tuck_planche",
    name: "Advanced Tuck Planche",
    category: "skill",
    level: 4,
    description: "Tuck planche with the knees pulled progressively further back — bridging toward the straddle planche.",
    prerequisites: ["tuck_planche"],
    progressions: ["straddle_planche"],
    targetHoldSeconds: 10,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Knees further back", "Straight arms", "Round upper back", "Lean more"],
    commonFaults: ["Knees to chest", "Bent arms", "Piked hips", "Not leaning enough"],
  },
  {
    id: "tuck_front_lever",
    name: "Tuck Front Lever",
    category: "skill",
    level: 4,
    description: "Hanging horizontal with knees tucked to the chest — the first complete front lever position.",
    prerequisites: ["hanging_leg_raise", "one_arm_hang"],
    progressions: ["advanced_tuck_front_lever", "front_lever"],
    targetHoldSeconds: 15,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Pull bar to hips", "Depress scapulae", "Tuck knees tight", "Body horizontal"],
    commonFaults: ["Arched back", "Bent arms", "Hips dropping", "Shrugging"],
  },
  {
    id: "advanced_tuck_front_lever",
    name: "Advanced Tuck Front Lever",
    category: "skill",
    level: 4,
    description: "Front lever with knees pulled back toward the hips — extending the lever arm on the road to full extension.",
    prerequisites: ["tuck_front_lever"],
    progressions: ["straddle_front_lever", "front_lever"],
    targetHoldSeconds: 10,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Knees pulled back", "Bar to hips", "Straight arms", "Keep body flat"],
    commonFaults: ["Knees to chest", "Piked hips", "Bent arms", "Not horizontal"],
  },
  {
    id: "straddle_front_lever",
    name: "Straddle Front Lever",
    category: "skill",
    level: 4,
    description: "Front lever with legs spread wide — a reduced lever arm before the straight full front lever.",
    prerequisites: ["advanced_tuck_front_lever"],
    progressions: ["front_lever"],
    targetHoldSeconds: 10,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Legs wide", "Open hips", "Bar to hips", "Body flat", "Point toes"],
    commonFaults: ["Piked hips", "Legs together", "Bent arms", "Arched back"],
  },
  {
    id: "skin_the_cat",
    name: "Skin the Cat",
    category: "skill",
    level: 4,
    description: "Rotating backward through a hang into an inverted hang and back — shoulder mobility for the back lever.",
    prerequisites: ["dead_hang", "parallel_support_hold"],
    progressions: ["german_hang", "back_lever"],
    targetReps: 5,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Start in support", "Swing through the middle", "Soft shoulders", "Control the return"],
    commonFaults: ["Rushing", "Bent arms", "Shoulder pain", "Using momentum"],
  },
  {
    id: "german_hang",
    name: "German Hang",
    category: "skill",
    level: 4,
    description: "Hanging upside down with arms behind the body — the shoulder rotation at the core of the back lever.",
    prerequisites: ["skin_the_cat"],
    progressions: ["tuck_back_lever", "back_lever"],
    targetHoldSeconds: 15,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Arms behind", "Rotate shoulders", "Relax into it", "Breathe"],
    commonFaults: ["Bent arms", "Shoulder strain", "Rushing", "Holding breath"],
  },
  {
    id: "tuck_back_lever",
    name: "Tuck Back Lever",
    category: "skill",
    level: 4,
    description: "Back lever position with knees tucked — the first full back lever shape.",
    prerequisites: ["german_hang"],
    progressions: ["back_lever"],
    targetHoldSeconds: 15,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Tuck knees", "Rotate shoulders back", "Straight arms", "Body horizontal"],
    commonFaults: ["Bent arms", "Piked hips", "Not horizontal", "Shoulder flexion loss"],
  },
];

// ============================================================================
// LEVEL 5: DEMI-GOD (Gravity-Defying)
// ============================================================================
export const LEVEL_5_EXERCISES: CalisthenicsExercise[] = [
  {
    id: "human_flag",
    name: "Human Flag",
    category: "skill",
    level: 5,
    description: "Holding body completely horizontal while gripping a vertical pole.",
    prerequisites: ["side_plank", "dragon_flag", "one_arm_hang"],
    progressions: ["flag_pullup", "flag_to_handstand"],
    targetHoldSeconds: 10,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Bottom hand pushes", "Top hand pulls", "Body straight", "Squeeze everything", "Look at bottom hand"],
    commonFaults: ["Bent body", "Bottom arm bends", "Sagging hips", "Grip failure"],
  },
  {
    id: "straddle_planche",
    name: "Straddle Planche",
    category: "skill",
    level: 5,
    description: "Holding body horizontal on hands with legs spread wide — reduced lever arm planche.",
    prerequisites: ["tuck_planche", "advanced_tuck_planche"],
    progressions: ["half_lay_planche", "full_planche"],
    targetHoldSeconds: 10,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Lean forward hard", "Straight arms", "Legs wide", "Open hips", "Round upper back"],
    commonFaults: ["Bent arms", "Piked hips", "Not leaning enough", "Bent elbows"],
  },
  {
    id: "front_lever",
    name: "Front Lever",
    category: "skill",
    level: 5,
    description: "Hanging from bar, holding entire body perfectly horizontal face up.",
    prerequisites: ["tuck_front_lever", "advanced_tuck_front_lever", "straddle_front_lever"],
    progressions: ["half_lay_front_lever", "full_front_lever", "front_lever_pullup"],
    targetHoldSeconds: 10,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Pull bar to hips", "Depress scapulae", "Body straight", "Legs together", "Point toes"],
    commonFaults: ["Bent arms", "Piked hips", "Arched back", "Not horizontal"],
  },
  {
    id: "back_lever",
    name: "Back Lever",
    category: "skill",
    level: 5,
    description: "Hanging from bar, holding body horizontal face down — German hang progression.",
    prerequisites: ["skin_the_cat", "german_hang", "tuck_back_lever"],
    progressions: ["straddle_back_lever", "full_back_lever"],
    targetHoldSeconds: 10,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Rotate shoulders back", "Straight arms", "Body straight", "Legs together", "Chin tucked"],
    commonFaults: ["Bent arms", "Piked hips", "Shoulder flexion loss", "Not horizontal"],
  },
  {
    id: "impossible_dip",
    name: "Impossible Dip",
    category: "push",
    level: 5,
    description: "Parallel bar dip but lowering forearms flat onto bars before pressing back up.",
    prerequisites: ["straight_bar_dip", "korean_dip", "weighted_dip"],
    progressions: ["impossible_dip_reps", "impossible_dip_weighted"],
    targetReps: 5,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Forearms to bars", "Elbows back", "Control descent", "Explosive press", "Straight arms"],
    commonFaults: ["Not touching bars", "Flared elbows", "Rushing", "Partial range"],
  },
  {
    id: "half_lay_planche",
    name: "Half-Lay Planche",
    category: "skill",
    level: 5,
    description: "Planche with legs extended halfway from the tuck — extending the lever arm between straddle and full planche.",
    prerequisites: ["straddle_planche"],
    progressions: ["full_planche"],
    targetHoldSeconds: 8,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Legs halfway", "Straight arms", "Round upper back", "Lean forward hard"],
    commonFaults: ["Bent arms", "Piked hips", "Legs too tucked", "Not enough lean"],
  },
  {
    id: "flag_pullup",
    name: "Flag Pull-up",
    category: "skill",
    level: 5,
    description: "Pulling while holding the human flag position — building the one-arm front lever pulling line.",
    prerequisites: ["human_flag", "one_arm_pullup"],
    progressions: ["one_arm_front_lever"],
    targetReps: 5,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Hold the flag", "Pull to the pole", "Keep the body straight", "Control the descent"],
    commonFaults: ["Bent body", "Partial pulls", "Losing the flag", "Using legs"],
  },
  {
    id: "maltese_tuck",
    name: "Maltese Tuck",
    category: "skill",
    level: 5,
    description: "Maltese-style hold with knees tucked — the wide-hand leverage strength behind the full maltese.",
    prerequisites: ["straddle_planche"],
    progressions: ["maltese"],
    targetHoldSeconds: 8,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Hands wide", "Tuck knees", "Maximum lean", "Locked elbows"],
    commonFaults: ["Bent arms", "Not wide enough", "Piked hips", "Shoulder failure"],
  },
  {
    id: "wide_planche",
    name: "Wide Planche",
    category: "skill",
    level: 5,
    description: "Full planche with hands set wider than shoulder width — the leverage bridge to the maltese and iron cross.",
    prerequisites: ["straddle_planche"],
    progressions: ["iron_cross", "maltese"],
    targetHoldSeconds: 5,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Hands wide", "Full extension", "Maximum lean", "Locked elbows"],
    commonFaults: ["Bent arms", "Piked hips", "Hands too narrow", "Not horizontal"],
  },
  {
    id: "iron_cross",
    name: "Iron Cross",
    category: "skill",
    level: 5,
    description: "Holding the body vertical between two supports with arms fully extended sideways — rings-level shoulder strength.",
    prerequisites: ["wide_planche"],
    progressions: ["victorian_cross"],
    targetHoldSeconds: 5,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Arms locked", "Press down and in", "Body straight", "Breathe"],
    commonFaults: ["Bent arms", "Shrugging", "Sinking", "Holding breath"],
  },
  {
    id: "victorian_tuck",
    name: "Victorian Tuck",
    category: "skill",
    level: 5,
    description: "Victorian position with knees tucked — the extreme shoulder extension prelude to the full victorian cross.",
    prerequisites: ["iron_cross"],
    progressions: ["victorian_cross"],
    targetHoldSeconds: 5,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Hands by hips", "Tuck knees", "Depress hard", "Total tension"],
    commonFaults: ["Bent arms", "Piked hips", "Hands not low", "Shoulder failure"],
  },
  {
    id: "one_arm_handstand",
    name: "One-Arm Handstand",
    category: "skill",
    level: 5,
    description: "Balancing the entire body on one hand — the pinnacle of hand balance.",
    prerequisites: ["freestanding_handstand"],
    progressions: ["one_arm_planche"],
    targetHoldSeconds: 10,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Weight on one hand", "False grip", "Tight core", "Adjust with fingers"],
    commonFaults: ["Falling", "Bent supporting arm", "Wrist strain", "Overbalancing"],
  },
  {
    id: "planche_pushup",
    name: "Planche Push-up",
    category: "push",
    level: 5,
    description: "Pressing up and down while holding the straddle planche — carrying planche strength into a full press.",
    prerequisites: ["straddle_planche"],
    progressions: ["one_arm_planche", "one_arm_planche_pushup"],
    targetReps: 5,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Keep the lean", "Straight arms at top", "Chest to floor", "Control the press"],
    commonFaults: ["Losing the lean", "Bent arms at top", "Piked hips", "Rushing"],
  },
];

// ============================================================================
// LEVEL 6: GOD LEVEL (Peak of Human Power)
// ============================================================================
export const LEVEL_6_EXERCISES: CalisthenicsExercise[] = [
  {
    id: "full_planche",
    name: "Full Planche",
    category: "skill",
    level: 6,
    description: "Holding body completely straight and horizontal, supported only by hands.",
    prerequisites: ["straddle_planche", "half_lay_planche"],
    progressions: ["one_arm_planche"],
    targetHoldSeconds: 5,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Maximum lean", "Locked elbows", "Body iron straight", "Fingers spread", "Breath shallow"],
    commonFaults: ["Bent arms", "Piked hips", "Not enough lean", "Bent legs"],
  },
  {
    id: "one_arm_front_lever",
    name: "One-Arm Front Lever",
    category: "skill",
    level: 6,
    description: "Holding perfect front lever using only one hand to grip the bar.",
    prerequisites: ["front_lever", "one_arm_pullup", "flag_pullup"],
    progressions: ["one_arm_front_lever_pullup"],
    targetHoldSeconds: 3,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Maximum depression", "Rotate toward bar", "Body iron straight", "Finger strength", "Total tension"],
    commonFaults: ["Bent arm", "Rotation", "Piked hips", "Grip slip"],
  },
  {
    id: "maltese",
    name: "Maltese Cross",
    category: "skill",
    level: 6,
    description: "Planche variation with hands placed much wider apart, mimicking rings cross on floor.",
    prerequisites: ["full_planche", "maltese_tuck", "wide_planche"],
    progressions: ["maltese_pushup", "maltese_press"],
    targetHoldSeconds: 3,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Hands wide", "Maximum lean", "Locked elbows", "Body horizontal", "External rotation"],
    commonFaults: ["Bent arms", "Not wide enough", "Piked hips", "Shoulder failure"],
  },
  {
    id: "victorian_cross",
    name: "Victorian Cross",
    category: "skill",
    level: 6,
    description: "Body horizontal on rings/bars with hands positioned down by hips — extreme lat/rear delt load.",
    prerequisites: ["maltese", "iron_cross", "victorian_tuck"],
    progressions: ["victorian_press"],
    targetHoldSeconds: 3,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Hands by hips", "Arms straight", "Depress hard", "Legs together", "Total body tension"],
    commonFaults: ["Bent arms", "Hands not low enough", "Piked hips", "Shoulder failure"],
  },
  {
    id: "one_arm_planche",
    name: "One-Arm Planche",
    category: "skill",
    level: 6,
    description: "Balancing entire horizontal body on a single hand — absolute pinnacle.",
    prerequisites: ["full_planche", "one_arm_handstand", "planche_pushup"],
    progressions: ["one_arm_planche_pushup"],
    targetHoldSeconds: 2,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Maximum finger strength", "Extreme lean", "Counterbalance", "Total body rigidity", "Zero wobble"],
    commonFaults: ["Falling", "Bent arm", "Hip break", "Finger slip"],
  },
];

// ============================================================================
// ALL CALISTHENICS EXERCISES COMBINED
// ============================================================================
export const ALL_CALISTHENICS_EXERCISES: CalisthenicsExercise[] = [
  ...LEVEL_0_EXERCISES,
  ...LEVEL_1_EXERCISES,
  ...LEVEL_2_EXERCISES,
  ...LEVEL_3_EXERCISES,
  ...LEVEL_4_EXERCISES,
  ...LEVEL_5_EXERCISES,
  ...LEVEL_6_EXERCISES,
];

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================
export function getExercisesByLevel(level: CalisthenicsLevel): CalisthenicsExercise[] {
  return ALL_CALISTHENICS_EXERCISES.filter(e => e.level === level);
}

export function getExercisesByCategory(category: CalisthenicsCategory): CalisthenicsExercise[] {
  return ALL_CALISTHENICS_EXERCISES.filter(e => e.category === category);
}

export function getExerciseById(id: string): CalisthenicsExercise | undefined {
  return ALL_CALISTHENICS_EXERCISES.find(e => e.id === id);
}

export function getPrerequisites(exerciseId: string): CalisthenicsExercise[] {
  const exercise = getExerciseById(exerciseId);
  if (!exercise) return [];
  return exercise.prerequisites.map(id => getExerciseById(id)!).filter(Boolean);
}

export function getNextProgressions(exerciseId: string): CalisthenicsExercise[] {
  const exercise = getExerciseById(exerciseId);
  if (!exercise) return [];
  return exercise.progressions.map(id => getExerciseById(id)!).filter(Boolean);
}

export function isExerciseUnlocked(exerciseId: string, completedExercises: Set<string>): boolean {
  const exercise = getExerciseById(exerciseId);
  if (!exercise) return false;
  return exercise.prerequisites.every(prereq => completedExercises.has(prereq));
}

export function getLevelName(level: CalisthenicsLevel): string {
  const names = {
    0: "None (Absolute Baseline)",
    1: "Beginner (Foundational Strength)",
    2: "Intermediate (The Golden Standard)",
    3: "Advanced (Skill Entry)",
    4: "Master (Elite Strength & Leverage)",
    5: "Demi-God (Gravity-Defying)",
    6: "God Level (Peak of Human Power)",
  };
  return names[level];
}

export function getLevelExercises(level: CalisthenicsLevel): CalisthenicsExercise[] {
  switch (level) {
    case 0: return LEVEL_0_EXERCISES;
    case 1: return LEVEL_1_EXERCISES;
    case 2: return LEVEL_2_EXERCISES;
    case 3: return LEVEL_3_EXERCISES;
    case 4: return LEVEL_4_EXERCISES;
    case 5: return LEVEL_5_EXERCISES;
    case 6: return LEVEL_6_EXERCISES;
    default: return [];
  }
}