// MMA/Combat Sports Curriculum
// Based on the 4-phase progression from the user's comprehensive data
// Pure TypeScript: zero React/DOM imports. Portable core for web/native.

export type MMALevel = "phase1" | "phase2" | "phase3" | "phase4";
export type MMACategory = "striking" | "grappling" | "wrestling" | "strength" | "conditioning" | "core" | "mental";

export interface MMAExercise {
  id: string;
  name: string;
  category: MMACategory;
  level: MMALevel;
  phase: number; // 1-4
  description: string;
  prerequisites: string[];
  progressions: string[];
  targetReps?: number;
  targetHoldSeconds?: number;
  targetSets?: number;
  restSeconds?: number;
  coachingCues: string[];
  commonFaults: string[];
  durationMinutes?: number; // For conditioning rounds
}

export const MMA_PHASE_1: MMAExercise[] = [
  // Striking Fundamentals
  {
    id: "shadowboxing_basic",
    name: "Shadowboxing (Basic)",
    category: "striking",
    level: "phase1",
    phase: 1,
    description: "1-2 (Jab-Cross), 1-2-3 (Jab-Cross-Hook) combinations focusing entirely on balance.",
    prerequisites: [],
    progressions: ["shadowboxing_intermediate"],
    targetSets: 3,
    durationMinutes: 3,
    restSeconds: 60,
    coachingCues: ["Stay balanced", "Hands up", "Turn hips on cross", "Return to guard"],
    commonFaults: ["Dropping hands", "Leaning", "No hip rotation", "Crossing feet"],
  },
  {
    id: "stance_wall_drill",
    name: "Stance Wall Drills",
    category: "striking",
    level: "phase1",
    phase: 1,
    description: "Holding fighting stance against wall to prevent over-extending or squaring up.",
    prerequisites: [],
    progressions: ["stance_movement_drill"],
    targetSets: 3,
    durationMinutes: 2,
    restSeconds: 60,
    coachingCues: ["Feet shoulder-width", "Lead toe to rear heel", "Knees bent", "Chin tucked"],
    commonFaults: ["Feet too narrow", "Too square", "Straight legs", "Chin up"],
  },
  {
    id: "heavy_bag_single",
    name: "Basic Heavy Bag Work",
    category: "striking",
    level: "phase1",
    phase: 1,
    description: "Single strikes (just jabs, just low kicks) to condition shins and knuckles.",
    prerequisites: ["shadowboxing_basic"],
    progressions: ["heavy_bag_combinations"],
    targetSets: 5,
    durationMinutes: 1,
    restSeconds: 60,
    coachingCues: ["Snap the jab", "Turn hip on kick", "Condition gradually", "Protect hands"],
    commonFaults: ["Hitting too hard", "Wrong part of shin", "Dropping hands", "No rotation"],
  },
  {
    id: "footwork_squares",
    name: "Footwork Squares",
    category: "striking",
    level: "phase1",
    phase: 1,
    description: "Moving forward, backward, left, and right without crossing feet.",
    prerequisites: [],
    progressions: ["footwork_circles", "footwork_lateral"],
    targetSets: 3,
    durationMinutes: 2,
    restSeconds: 60,
    coachingCues: ["Step-drag", "Never cross feet", "Stay in stance", "Eyes forward"],
    commonFaults: ["Crossing feet", "Too wide", "Bouncing", "Looking down"],
  },

  // Grappling & Wrestling Base
  {
    id: "bridging",
    name: "Bridging",
    category: "grappling",
    level: "phase1",
    phase: 1,
    description: "Lying on back, exploding hips upward to build glute and neck strength.",
    prerequisites: [],
    progressions: ["bridging_with_reach"],
    targetReps: 15,
    targetSets: 3,
    restSeconds: 60,
    coachingCues: ["Feet close to hips", "Drive through heels", "Chin to chest", "Explosive hips"],
    commonFaults: ["Not driving hips", "Head not tucked", "Slow movement", "Feet too far"],
  },
  {
    id: "shrimping",
    name: "Shrimping (Hip Escape)",
    category: "grappling",
    level: "phase1",
    phase: 1,
    description: "Foundational movement used to escape bottom positions on the ground.",
    prerequisites: [],
    progressions: ["shrimp_to_guard", "shrimp_to_knees"],
    targetReps: 20,
    targetSets: 3,
    restSeconds: 60,
    coachingCues: ["Turn on side", "Push off foot", "Hip away", "Frame with arms"],
    commonFaults: ["Flat on back", "Not turning", "Weak push", "Arms not framing"],
  },
  {
    id: "technical_standup",
    name: "Technical Stand-up",
    category: "grappling",
    level: "phase1",
    phase: 1,
    description: "Rising from floor safely while maintaining guard structure.",
    prerequisites: ["shrimping"],
    progressions: ["standup_under_pressure"],
    targetReps: 10,
    targetSets: 3,
    restSeconds: 60,
    coachingCues: ["Post on hand", "Hip up", "Swing leg through", "Guard up"],
    commonFaults: ["Dropping hands", "Not posting", "Slow", "Wrong leg"],
  },
  {
    id: "sprawls_solo",
    name: "Sprawls (Solo)",
    category: "wrestling",
    level: "phase1",
    phase: 1,
    description: "Dropping hips to floor quickly to defend imaginary takedown.",
    prerequisites: [],
    progressions: ["sprawl_to_front_headlock"],
    targetReps: 15,
    targetSets: 3,
    restSeconds: 60,
    coachingCues: ["Hips to floor", "Chest up", "Hands wide", "Explosive back up"],
    commonFaults: ["Slow", "Hips high", "Hands not wide", "Not chest up"],
  },

  // Strength, Conditioning & Core
  {
    id: "roadwork_aerobic",
    name: "Roadwork (Aerobic Base)",
    category: "conditioning",
    level: "phase1",
    phase: 1,
    description: "3-5 mile steady-state jogging for lung capacity.",
    prerequisites: [],
    progressions: ["roadwork_tempo"],
    durationMinutes: 30,
    targetSets: 1,
    coachingCues: ["Conversational pace", "Nose breathing", "Relaxed shoulders", "Consistent pace"],
    commonFaults: ["Too fast", "Mouth breathing", "Tense shoulders", "Inconsistent"],
  },
  {
    id: "bodyweight_pyramids",
    name: "Bodyweight Pyramids",
    category: "strength",
    level: "phase1",
    phase: 1,
    description: "Push-ups, air squats, and pull-ups in ascending/descending rep schemes.",
    prerequisites: [],
    progressions: ["weighted_pyramids"],
    targetSets: 3,
    restSeconds: 90,
    coachingCues: ["Perfect form", "Controlled tempo", "Full ROM", "Scale as needed"],
    commonFaults: ["Sacrificing form", "Rushing", "Incomplete ROM", "Uneven pyramids"],
  },
  {
    id: "plank_variations",
    name: "Plank Variations",
    category: "core",
    level: "phase1",
    phase: 1,
    description: "Standard, side, and RKC planks for static core stability.",
    prerequisites: [],
    progressions: ["plank_reach", "plank_row"],
    targetHoldSeconds: 60,
    targetSets: 3,
    restSeconds: 60,
    coachingCues: ["Posterior pelvic tilt", "Squeeze glutes", "Active shoulders", "Breathe"],
    commonFaults: ["Sagging", "Piking", "Shoulders shrugged", "Holding breath"],
  },
  {
    id: "medball_slams",
    name: "Medicine Ball Slams",
    category: "conditioning",
    level: "phase1",
    phase: 1,
    description: "Developing foundational explosive power.",
    prerequisites: [],
    progressions: ["medball_rotational", "medball_chest_pass"],
    targetReps: 10,
    targetSets: 3,
    restSeconds: 60,
    coachingCues: ["Full extension", "Slam hard", "Catch on bounce", "Reset each rep"],
    commonFaults: ["Not extending", "Soft slam", "Rounding back", "Catching awkwardly"],
  },
];

export const MMA_PHASE_2: MMAExercise[] = [
  // Striking Progressions
  {
    id: "thai_pad_work",
    name: "Thai Pad Work",
    category: "striking",
    level: "phase2",
    phase: 2,
    description: "Executing multi-limb combinations (Punch-Kick-Clinch) with a partner.",
    prerequisites: ["shadowboxing_basic", "heavy_bag_single"],
    progressions: ["thai_pad_advanced"],
    targetSets: 5,
    durationMinutes: 3,
    restSeconds: 60,
    coachingCues: ["Hit through pads", "Hold for partner", "Communicate", "Match intensity"],
    commonFaults: ["Holding back", "Bad pad holding", "No communication", "Lazy feet"],
  },
  {
    id: "dutch_kickboxing_drills",
    name: "Dutch Kickboxing Drills",
    category: "striking",
    level: "phase2",
    phase: 2,
    description: "Block-and-counter drills with a partner wearing big gloves.",
    prerequisites: ["shadowboxing_basic", "footwork_squares"],
    progressions: ["dutch_sparring"],
    targetSets: 5,
    durationMinutes: 3,
    restSeconds: 60,
    coachingCues: ["Block then fire", "Small movements", "Counter immediately", "Stay balanced"],
    commonFaults: ["Late blocks", "Big movements", "Late counters", "Overcommitting"],
  },
  {
    id: "slip_counter_drills",
    name: "Slip & Counter Drills",
    category: "striking",
    level: "phase2",
    phase: 2,
    description: "Using a slip-rope or partner to practice head movement while striking.",
    prerequisites: ["shadowboxing_basic"],
    progressions: ["slip_counter_sparring"],
    targetSets: 5,
    durationMinutes: 3,
    restSeconds: 60,
    coachingCues: ["Small slip", "Eyes on target", "Counter off slip", "Stay in range"],
    commonFaults: ["Big slips", "Looking away", "Late counters", "Dropping hands"],
  },
  {
    id: "cage_cutting_footwork",
    name: "Cage Cutting Footwork",
    category: "striking",
    level: "phase2",
    phase: 2,
    description: "Learning how to trap an opponent against the gym walls.",
    prerequisites: ["footwork_squares"],
    progressions: ["cage_cutting_sparring"],
    targetSets: 5,
    durationMinutes: 3,
    restSeconds: 60,
    coachingCues: ["Lateral first", "Cut angle", "Don't chase", "Pressure constant"],
    commonFaults: ["Chasing straight", "No angle", "Too close", "No pressure"],
  },

  // Grappling & Wrestling Progressions
  {
    id: "wall_walking",
    name: "Wall Walking",
    category: "wrestling",
    level: "phase2",
    phase: 2,
    description: "Using the cage wall to stand up from the bottom position.",
    prerequisites: ["technical_standup", "bridging"],
    progressions: ["wall_walk_under_pressure"],
    targetReps: 10,
    targetSets: 3,
    restSeconds: 60,
    coachingCues: ["Back to wall", "Walk feet up", "Frame hip", "Explode up"],
    commonFaults: ["Not framing", "Slow", "Giving up back", "Not exploding"],
  },
  {
    id: "shooting_drills",
    name: "Shooting Drills",
    category: "wrestling",
    level: "phase2",
    phase: 2,
    description: "Double-leg and single-leg takedown entries against a moving partner.",
    prerequisites: ["sprawls_solo"],
    progressions: ["chain_wrestling"],
    targetReps: 20,
    targetSets: 3,
    restSeconds: 60,
    coachingCues: ["Level change", "Penetration step", "Head to hip", "Drive through"],
    commonFaults: ["High level", "Short step", "Head out", "Stopping drive"],
  },
  {
    id: "chain_drilling",
    name: "Chain Drilling",
    category: "grappling",
    level: "phase2",
    phase: 2,
    description: "Transitioning fluidly from a submission attempt directly into a sweep.",
    prerequisites: ["shrimping", "technical_standup"],
    progressions: ["flow_rolling"],
    targetReps: 10,
    targetSets: 3,
    restSeconds: 60,
    coachingCues: ["Flow don't force", "Chain attacks", "React to defense", "Stay tight"],
    commonFaults: ["Forcing", "Single attacks", "Giving up position", "Loose"],
  },
  {
    id: "pummeling",
    name: "Pummeling",
    category: "grappling",
    level: "phase2",
    phase: 2,
    description: "Dynamic upper-body battling for underhooks and inside position.",
    prerequisites: ["technical_standup"],
    progressions: ["pummeling_to_takedown"],
    targetSets: 5,
    durationMinutes: 2,
    restSeconds: 60,
    coachingCues: ["Swim inside", "Chest to chest", "Constant motion", "Head position"],
    commonFaults: ["Outside position", "Static", "No head control", "Giving up underhooks"],
  },

  // Strength, Conditioning & Core
  {
    id: "barbell_basics",
    name: "Barbell Basics",
    category: "strength",
    level: "phase2",
    phase: 2,
    description: "Clean & Press, Deadlifts, and Front Squats for raw force production.",
    prerequisites: ["bodyweight_pyramids"],
    progressions: ["barbell_power"],
    targetReps: 5,
    targetSets: 5,
    restSeconds: 180,
    coachingCues: ["Perfect form", "Explosive", "Full ROM", "Progressive overload"],
    commonFaults: ["Rounding back", "Not explosive", "Partial ROM", "Ego lifting"],
  },
  {
    id: "kettlebell_flows",
    name: "Kettlebell Flows",
    category: "conditioning",
    level: "phase2",
    phase: 2,
    description: "Snatches, cleans, and Turkish Get-ups for shoulder stability and endurance.",
    prerequisites: ["medball_slams"],
    progressions: ["kettlebell_complexes"],
    targetSets: 3,
    durationMinutes: 10,
    restSeconds: 60,
    coachingCues: ["Flow smoothly", "Hip hinge", "Pack shoulder", "Breathe"],
    commonFaults: ["Jerking", "Loose core", "Bad rack", "Holding breath"],
  },
  {
    id: "hiit_sprints",
    name: "HIIT Sprints",
    category: "conditioning",
    level: "phase2",
    phase: 2,
    description: "800m repeats and hill sprints to build a powerful anaerobic engine.",
    prerequisites: ["roadwork_aerobic"],
    progressions: ["hiit_complex"],
    targetSets: 8,
    durationMinutes: 2,
    restSeconds: 120,
    coachingCues: ["Max effort", "Full recovery", "Consistent times", "Form holds"],
    commonFaults: ["Pacing", "Incomplete rest", "Form breakdown", "Quitting early"],
  },
  {
    id: "hanging_leg_raises",
    name: "Hanging Leg Raises",
    category: "core",
    level: "phase2",
    phase: 2,
    description: "Dynamic core strength to handle the weight of an opponent.",
    prerequisites: ["lying_leg_raise", "hanging_knee_raise"],
    progressions: ["toes_to_bar", "windshield_wiper"],
    targetReps: 12,
    targetSets: 3,
    restSeconds: 90,
    coachingCues: ["Straight legs", "Toes to bar", "Control down", "No swing"],
    commonFaults: ["Bent knees", "Swinging", "Partial ROM", "Grip failure"],
  },
];

export const MMA_PHASE_3: MMAExercise[] = [
  // Striking Depth
  {
    id: "situational_sparring",
    name: "Situational Sparring",
    category: "striking",
    level: "phase3",
    phase: 3,
    description: "Sparring with constraints (e.g., one person can only use jabs; sparring only against the cage).",
    prerequisites: ["thai_pad_work", "dutch_kickboxing_drills"],
    progressions: ["free_sparring"],
    targetSets: 5,
    durationMinutes: 5,
    restSeconds: 60,
    coachingCues: ["Honor constraints", "Problem solve", "Adapt", "Stay technical"],
    commonFaults: ["Breaking rules", "Going too hard", "Ignoring constraints", "Ego"],
  },
  {
    id: "interception_drills",
    name: "Interception Drills",
    category: "striking",
    level: "phase3",
    phase: 3,
    description: "Catching kicks and countering instantly with strikes or takedowns.",
    prerequisites: ["slip_counter_drills", "dutch_kickboxing_drills"],
    progressions: ["interception_sparring"],
    targetSets: 5,
    durationMinutes: 3,
    restSeconds: 60,
    coachingCues: ["Catch don't block", "Immediate counter", "Balance", "Choose counter"],
    commonFaults: ["Blocking not catching", "Late counter", "Off balance", "Hesitation"],
  },
  {
    id: "dirty_boxing_clinch",
    name: "Dirty Boxing / Clinch Knees",
    category: "striking",
    level: "phase3",
    phase: 3,
    description: "Striking while controlling the back of the opponent's neck (Muay Thai plumb).",
    prerequisites: ["thai_pad_work", "pummeling"],
    progressions: ["clinch_sparring"],
    targetSets: 5,
    durationMinutes: 3,
    restSeconds: 60,
    coachingCues: ["Control head", "Pull down", "Knee through", "Off-balance them"],
    commonFaults: ["Weak control", "Straight knees", "No off-balancing", "Standing tall"],
  },
  {
    id: "feinting_matrices",
    name: "Feinting Matrices",
    category: "striking",
    level: "phase3",
    phase: 3,
    description: "Incorporating eye, hip, and hand feints to mask actual attacks.",
    prerequisites: ["slip_counter_drills", "footwork_squares"],
    progressions: ["feinting_sparring"],
    targetSets: 5,
    durationMinutes: 3,
    restSeconds: 60,
    coachingCues: ["Sell the feint", "Eyes lie", "Hips tell truth", "Immediate real attack"],
    commonFaults: ["Obvious feints", "No real attack", "Telegraphing", "Too slow"],
  },

  // Grappling & Wrestling Depth
  {
    id: "defensive_cage_wrestling",
    name: "Defensive Cage Wrestling",
    category: "wrestling",
    level: "phase3",
    phase: 3,
    description: "Surviving and reversing position when pinned flat against the fence.",
    prerequisites: ["wall_walking", "sprawls_solo"],
    progressions: ["cage_wrestling_offense"],
    targetSets: 5,
    durationMinutes: 5,
    restSeconds: 60,
    coachingCues: ["Frame hips", "Underhook", "Wall walk", "Reverse position"],
    commonFaults: ["Flat on cage", "No frames", "Giving up back", "Panic"],
  },
  {
    id: "mat_returns",
    name: "Mat Returns",
    category: "wrestling",
    level: "phase3",
    phase: 3,
    description: "Lifting and slamming an opponent who is actively trying to stand up.",
    prerequisites: ["shooting_drills", "barbell_basics"],
    progressions: ["mat_return_chain"],
    targetReps: 10,
    targetSets: 3,
    restSeconds: 60,
    coachingCues: ["Hip pop", "Control descent", "Stay on top", "Chain to control"],
    commonFaults: ["No hip pop", "Slamming uncontrolled", "Losing top", "Giving space"],
  },
  {
    id: "scramble_drills",
    name: "Scramble Drills",
    category: "grappling",
    level: "phase3",
    phase: 3,
    description: "Continuous, high-paced wrestling where neither fighter settles for a position.",
    prerequisites: ["chain_drilling", "flow_rolling"],
    progressions: ["scramble_sparring"],
    targetSets: 5,
    durationMinutes: 5,
    restSeconds: 60,
    coachingCues: ["Move constantly", "Create scrambles", "Don't settle", "Chain transitions"],
    commonFaults: ["Stalling", "Settling", "Single moves", "Gas out"],
  },
  {
    id: "advanced_leg_locks",
    name: "Advanced Leg Lock Entries",
    category: "grappling",
    level: "phase3",
    phase: 3,
    description: "Imanari rolls and K-guard entries to threaten the lower limbs.",
    prerequisites: ["chain_drilling", "shrimping"],
    progressions: ["leg_lock_sparring"],
    targetReps: 10,
    targetSets: 3,
    restSeconds: 60,
    coachingCues: ["Entry angle", "Control knee line", "Finish mechanics", "Safety first"],
    commonFaults: ["Bad entry", "No knee control", "Rushing finish", "Ignoring safety"],
  },

  // Strength, Conditioning & Core
  {
    id: "olympic_lifting",
    name: "Olympic Lifting",
    category: "strength",
    level: "phase3",
    phase: 3,
    description: "Power Cleans and Snatches for peak velocity and hip extension.",
    prerequisites: ["barbell_basics"],
    progressions: ["olympic_complexes"],
    targetReps: 3,
    targetSets: 5,
    restSeconds: 180,
    coachingCues: ["Speed under bar", "Triple extension", "Catch tight", "Full extension"],
    commonFaults: ["Slow", "Early arm bend", "Not catching tight", "Forward jump"],
  },
  {
    id: "airdyno_rowing_intervals",
    name: "Airdyne/Rowing Intervals",
    category: "conditioning",
    level: "phase3",
    phase: 3,
    description: "5-minute rounds of max effort to simulate exact cardio demands of a fight.",
    prerequisites: ["hiit_sprints"],
    progressions: ["fight_simulation_conditioning"],
    targetSets: 5,
    durationMinutes: 5,
    restSeconds: 60,
    coachingCues: ["Pace for round", "Sprint last 30s", "Mental toughness", "Breath control"],
    commonFaults: ["Too fast early", "Quitting", "Pacing wrong", "Mental break"],
  },
  {
    id: "weighted_carries",
    name: "Weighted Carries",
    category: "strength",
    level: "phase3",
    phase: 3,
    description: "Farmer's walks and Zercher carries to simulate lifting human bodies.",
    prerequisites: ["barbell_basics", "kettlebell_flows"],
    progressions: ["heavy_carries"],
    targetSets: 3,
    durationMinutes: 2,
    restSeconds: 120,
    coachingCues: ["Posture tall", "Core braced", "Heel-toe walk", "Don't rush"],
    commonFaults: ["Leaning", "Soft core", "Short steps", "Dropping weight"],
  },
  {
    id: "landmine_twists",
    name: "Landmine Twists",
    category: "core",
    level: "phase3",
    phase: 3,
    description: "Rotational core power for throwing devastating hooks and throws.",
    prerequisites: ["plank_variations", "medball_rotational"],
    progressions: ["landmine_complex"],
    targetReps: 10,
    targetSets: 3,
    restSeconds: 60,
    coachingCues: ["Rotate hips", "Arms straight", "Explosive", "Full rotation"],
    commonFaults: ["Bending arms", "No hip rotation", "Soft core", "Partial rotation"],
  },
];

export const MMA_PHASE_4: MMAExercise[] = [
  // God Level MMA Matrix
  {
    id: "shark_tank_sparring",
    name: "Shark Tank Sparring",
    category: "striking",
    level: "phase4",
    phase: 4,
    description: "Fresh opponents rotate in every 60 seconds to break you mentally and physically.",
    prerequisites: ["situational_sparring", "free_sparring"],
    progressions: [],
    targetSets: 10,
    durationMinutes: 1,
    restSeconds: 60,
    coachingCues: ["Survive", "Adapt", "Conserve energy", "Mental fortress"],
    commonFaults: ["Quitting", "Panic", "Technique breakdown", "No strategy"],
  },
  {
    id: "blindfolded_reflex",
    name: "Blindfolded Reflex Drills",
    category: "striking",
    level: "phase4",
    phase: 4,
    description: "Developing spatial awareness and audio-tactile responses to cage positioning.",
    prerequisites: ["slip_counter_drills", "interception_drills"],
    progressions: [],
    targetSets: 5,
    durationMinutes: 3,
    restSeconds: 60,
    coachingCues: ["Listen", "Feel pressure", "React don't think", "Trust instincts"],
    commonFaults: ["Panic", "Freezing", "Overthinking", "Losing balance"],
  },
  {
    id: "ten_minute_escape",
    name: "The 10-Minute Escape",
    category: "grappling",
    level: "phase4",
    phase: 4,
    description: "Starting from the absolute worst position (mounted/back taken) against a heavier opponent with 0 rest.",
    prerequisites: ["defensive_cage_wrestling", "scramble_drills"],
    progressions: [],
    targetSets: 1,
    durationMinutes: 10,
    restSeconds: 0,
    coachingCues: ["Survive first", "Frame everything", "Create space", "Chain escapes", "Never quit"],
    commonFaults: ["Panic", "Giving up", "Wasting energy", "No frames", "Stopping"],
  },
  {
    id: "high_altitude_chain_takedowns",
    name: "High-Altitude Chain Takedowns",
    category: "wrestling",
    level: "phase4",
    phase: 4,
    description: "3 minutes of non-stop explosive double-legs while wearing altitude simulation or under extreme fatigue.",
    prerequisites: ["shooting_drills", "hiit_sprints"],
    progressions: [],
    targetSets: 1,
    durationMinutes: 3,
    restSeconds: 0,
    coachingCues: ["Explosive every rep", "Level change", "Drive through", "Breathe"],
    commonFaults: ["Slowing down", "Technique breakdown", "Quitting", "Bad level changes"],
  },
  {
    id: "sledgehammer_tire_circuits",
    name: "Sledgehammer / Tire Circuits",
    category: "conditioning",
    level: "phase4",
    phase: 4,
    description: "Build violent, rotational endurance that mimics ground-and-pound striking.",
    prerequisites: ["medball_slams", "kettlebell_flows"],
    progressions: [],
    targetSets: 5,
    durationMinutes: 3,
    restSeconds: 60,
    coachingCues: ["Rotate hips", "Slam hard", "Full rotation", "Switch sides"],
    commonFaults: ["Arms only", "Soft swings", "No rotation", "Poor footwork"],
  },
  {
    id: "complex_contrast_training",
    name: "Complex Contrast Training",
    category: "strength",
    level: "phase4",
    phase: 4,
    description: "Max-effort heavy lift (e.g., 3-rep Max Squat) immediately followed by explosive movement (e.g., Box Jumps).",
    prerequisites: ["barbell_basics", "hiit_sprints"],
    progressions: [],
    targetSets: 4,
    restSeconds: 180,
    coachingCues: ["Heavy first", "Explosive second", "Minimal rest", "Neural priming"],
    commonFaults: ["Too heavy", "Not explosive", "Too much rest", "Form breakdown"],
  },
  {
    id: "towel_pullups",
    name: "Towel/Gi Pull-ups",
    category: "core",
    level: "phase4",
    phase: 4,
    description: "Developing 'isometric death-grip' strength so opponents cannot break your clamps.",
    prerequisites: ["hanging_leg_raises", "weighted_pullups"],
    progressions: ["one_arm_towel_pullup"],
    targetReps: 5,
    targetSets: 3,
    restSeconds: 180,
    coachingCues: ["Grip hard", "Full ROM", "Control", "Death grip"],
    commonFaults: ["Kipping", "Partial ROM", "Loose grip", "Giving up"],
  },
  {
    id: "iron_neck_bridges",
    name: "Iron Neck / Weighted Bridges",
    category: "mental",
    level: "phase4",
    phase: 4,
    description: "Neck conditioning required to absorb heavy strikes and prevent concussions.",
    prerequisites: ["bridging"],
    progressions: [],
    targetReps: 20,
    targetSets: 3,
    restSeconds: 60,
    coachingCues: ["Slow controlled", "Full range", "Neutral spine", "Progressive load"],
    commonFaults: ["Rushing", "Hyperextension", "Too heavy", "Jerking"],
  },
];

export const ALL_MMA_EXERCISES = [
  ...MMA_PHASE_1,
  ...MMA_PHASE_2,
  ...MMA_PHASE_3,
  ...MMA_PHASE_4,
];

export function getMMAExercisesByPhase(phase: number): MMAExercise[] {
  switch (phase) {
    case 1: return MMA_PHASE_1;
    case 2: return MMA_PHASE_2;
    case 3: return MMA_PHASE_3;
    case 4: return MMA_PHASE_4;
    default: return [];
  }
}

export function getMMAExercisesByCategory(category: string): MMAExercise[] {
  return ALL_MMA_EXERCISES.filter(e => e.category === category);
}

export function getMMAExerciseById(id: string): MMAExercise | undefined {
  return ALL_MMA_EXERCISES.find(e => e.id === id);
}